### ISSUE TITLE
Geoscape time ticks when in Squad Select from Barracks

### ISSUE THREAD

**Issue by BlackRose39** [WOTCStrategyOverhaul/SquadSelectAnytime#1]
Hello! Thanks for the mod. I just wanted to report a bug that during squad select, when opened from the barracks, the time in the geoscape actually ticks. While I was customizing my squad in there, a dark event completed and was interrupting there. 

Thanks!
-Black Rose

**Comment by Xymanek** [comment]
*sigh* I'm actually very well aware of this issue, this happens when existing the squad select screen (time is advanced by 60-70 secs). It's not just this mod, normally canceling mission loadout causes same thing but it's never noticeable since you always exit back to geoscape. I do intend to track the source of this behaviour eventually but there are more just important things to right now....

BTW, when exactly did the dark event popup appear?

**Comment by Xymanek** [comment]
The fix is up on workshop. Credits to robojumper for finding the cause of the problem
